### ISSUE TITLE
중앙의 색상 바 위치 및 크기 수정하기

### ISSUE THREAD

**Issue by Gijuno** [Gijuno/dimi-alarm#12]

**Comment by Gijuno** [comment]
## How to 밑줄 위치
- 텍스트 노드를 relative로 만든다, z-index 1
- 텍스트노드에 After 가상엘리먼트를 만들다
- After를 absolute로 만들고 bottom이 0, left가 0, width 100%, right 0,
- background color 주고, height: 24
- z-index - 1

**Comment by Gijuno** [comment]
@Im-Siyoun 해주실래요..?

**Comment by Im-Siyoun** [comment]
돌겠군
